---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'sonarr_exporter'
    static_configs:
      - targets: ['sonarrexporter:9715']
    relabel_configs:
      - target_label: 'sonarr_name'
        replacement: 'sonarr'

  - job_name: 'radarr_exporter'
    static_configs:
      - targets: ['radarrexporter:9715']
    relabel_configs:
      - target_label: 'sonarr_name'
        replacement: 'radarr'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'pitemp'
    static_configs:
      - targets: ['mole.lan:8080']

  - job_name: 'blackbox'
    metrics_path: '/probe'
    scrape_interval: 1m
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://prometheus.io
          - https://prometheus.io
          - http://www.google.com/gen_204
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: "pikvm"
    metrics_path: "/api/export/prometheus/metrics"
    basic_auth:
      username: admin
      password_file: pikvm.password
    static_configs:
      - targets: ['pikvm']
    tls_config:
      insecure_skip_verify: true  # For self-signed certificate


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
